#
# Claude Code Zen - Local NPM Registry Configuration
# This file configures Verdaccio for local package testing and private package hosting
#

#
# Storage path for packages
#
storage: ./storage

#
# Authentication (htpasswd)
#
auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+infinity".
    # You can set this to -1 to disable registration.
    # max_users: 1000

#
# Security settings
#
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 1h

#
# Server configuration
#
listen:
  - 0.0.0.0:4873

#
# Web UI configuration
#
web:
  title: Claude Code Zen Registry
  logo: logo.png
  primary_color: "#4285f4"
  scope: "@claude-zen"

#
# Package access and publish configuration
# No authentication required - behind firewall
#
packages:
  # Claude-zen scoped packages - no auth required
  '@claude-zen/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  # All other packages (fallback to npmjs)
  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

#
# Proxy configuration for public npm packages
#
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 100s

#
# Logs configuration
#
log:
  type: stdout
  format: pretty
  level: info

#
# Middleware
#
middlewares:
  audit:
    enabled: true

#
# Notifications
#
notify:
  method: POST
  headers: [{ "Content-Type": "application/json" }]
  endpoint: http://localhost:3000/api/v1/registry/notify
  content: '{"package": "{{name}}", "version": "{{version}}", "action": "{{action}}"}'

#
# Experiments (enable new features)
#
experiments:
  search: true
  token: false