# GitHub Copilot MCP External Server Configuration
# Following GitHub's recommendations for copilot coding agent setup
# Reference: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/extend-coding-agent-with-mcp

mcp_servers:
  # External Research and Analysis Tools
  context7:
    url: "https://mcp.context7.com/mcp"
    transport: "http"
    description: "Research and analysis tools for enhanced development workflow"
    capabilities:
      - research
      - analysis
      - documentation
      - code_review
    timeout: 30000
    retry_attempts: 3
    
  # Knowledge Base and Documentation
  deepwiki:
    url: "https://mcp.deepwiki.com/sse"
    transport: "sse"
    description: "Knowledge base and documentation research tools"
    capabilities:
      - knowledge_search
      - documentation
      - research
      - reference_lookup
    timeout: 30000
    retry_attempts: 3
    
  # Git Operations and Repository Management
  gitmcp:
    url: "https://gitmcp.io/docs"
    transport: "http"
    description: "Git operations and repository management tools"
    capabilities:
      - git_operations
      - repository_analysis
      - branch_management
      - merge_assistance
    timeout: 30000
    retry_attempts: 3
    
  # Code Analysis and Security Scanning
  semgrep:
    url: "https://mcp.semgrep.ai/sse"
    transport: "sse"
    description: "Code analysis and security scanning for code quality"
    capabilities:
      - security_analysis
      - code_quality
      - vulnerability_detection
      - best_practices
    timeout: 30000
    retry_attempts: 3

# Copilot integration settings
copilot:
  enable_external_mcp: true
  prioritize_external_tools: true
  fallback_to_local: true
  tool_discovery_timeout: 10000
  max_concurrent_requests: 10
  
  # Tool preference order for overlapping capabilities
  tool_preference:
    research: ["context7", "deepwiki"]
    code_analysis: ["semgrep"]
    git_operations: ["gitmcp"]
    documentation: ["deepwiki", "context7"]
    security: ["semgrep"]

# Error handling and reliability
error_handling:
  retry_failed_requests: true
  max_retries: 3
  retry_delay: 1000
  circuit_breaker_threshold: 5
  fallback_strategy: "local_only"
  
# Monitoring and logging
monitoring:
  log_mcp_requests: true
  track_tool_usage: true
  performance_metrics: true
  alert_on_failures: true

# Security settings
security:
  validate_server_certificates: true
  require_https_for_external: true
  timeout_external_requests: 30000
  rate_limit_per_server: 100