[package]
name = "claude-zen-neural-learning"
version = "0.1.0"
edition = "2021"
authors = ["claude-code-zen Team"]
description = "WASM neural learning engine for claude-zen swarm intelligence"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
js-sys = "0.3.70"
console_error_panic_hook = "0.1.7"
wasm-logger = "0.2.0"
log = "0.4.21"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
thiserror = "1.0.50"

# For typed arrays support
getrandom = { version = "0.2", features = ["js"] }

# Internal FANN implementation - references the existing core
claude-zen-neural = { path = "../core" }

[dependencies.web-sys]
version = "0.3.70"
features = [
  "console",
  "Performance",
  "Window",
]

[features]
default = ["console_error_panic_hook"]
cascade = ["claude-zen-neural/cascade"]

# For wasm-pack optimization
[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
# Link Time Optimization for better performance and smaller size
lto = true
# Strip debug symbols
strip = true