[package]
name = "coder"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Zenflow contributors"]
description = "Rust-only coder binary that wraps the code-mesh engine"

[[bin]]
name = "coder"
path = "src/main.rs"

[dependencies]
code-mesh-core = { path = "../../crates/code-mesh-core" }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "cargo"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }