[tools]
node = "22.17.1"  # Latest Node.js with ES modules and crypto.randomUUID
pnpm = "latest"
rust = "1.89.0"

[env]
NODE_OPTIONS = "--experimental-vm-modules --experimental-wasm-modules"
NPM_CONFIG_ENGINE_STRICT = "true"
RUST_BACKTRACE = "1"
RUSTFLAGS = "-C target-cpu=native"  # Optimize for local CPU

