// Simple ESLint 9 Flat Config for Claude Zen
export default [
  // Base config for all files
  {
    name: 'claude-zen/base',
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
      },
    },
  },
  // JavaScript and TypeScript files
  {
    name: 'claude-zen/javascript-typescript',
    files: ['**/*.js', '**/*.mjs', '**/*.cjs', '**/*.ts', '**/*.tsx'],
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'prefer-const': 'warn',
      'no-var': 'error',
      'no-undef': 'warn',
      'no-unreachable': 'warn',
      'no-redeclare': 'warn',
      'no-duplicate-imports': 'warn',
    },
  },
  // Test files
  {
    name: 'claude-zen/tests',
    files: [
      '**/*.test.js',
      '**/*.test.ts',
      '**/*.spec.js',
      '**/*.spec.ts',
      '**/__tests__/**/*',
      '**/tests/**/*',
      'test/**/*',
    ],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
      },
    },
    rules: {
      'no-unused-expressions': 'off',
      'no-console': 'off',
    },
  },
  // Ignore patterns
  {
    name: 'claude-zen/ignores',
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      '.hive-mind/**',
      '.swarm/**',
      'logs/**',
      'target/**',
      'temp-js/**',
      'archive/**',
      'examples/**/node_modules/**',
      '**/*.min.js',
      'ruv-swarm/**',
      'native/**',
      'claude-zen-mcp/**',
      'vision-to-code/**',
      'services/**',
      'benchmark/**/*.py',
      'infrastructure/**',
      'docker/**',
      '*.wgsl',
      '*.rs',
      '*.lock',
      '*.log',
      '*.db',
      '*.tgz',
      '*.dump',
      'scripts/test-monorepo-detection.js',
      '**/*.d.ts',
      '*.config.js.backup',
    ],
  },
];