[tools]
node = "22.17.1"
npm = "10"

# Align with claude-zen strategy:
# - Node 22+ (matches engines requirement in package.json)  
# - npm 10+ (matches engines requirement in package.json)
# - Consistent with .mise.toml specification
