packages:
  - apps/*
  - packages/foundation
  - packages/llm-providers
  - packages/development
  - packages/enterprise
  - packages/infrastructure
  - packages/intelligence
  - packages/operations
  - packages/repo-analyzer
  - packages/language-parsers
  - packages/ai-linter
  - packages/implementation-packages/*
  - '!apps/*-backup'

catalog:
  '@claude-zen/development': workspace:*
  '@claude-zen/enterprise': workspace:*
  '@claude-zen/foundation': workspace:*
  '@claude-zen/infrastructure': workspace:*
  '@claude-zen/intelligence': workspace:*
  '@claude-zen/llm-providers': workspace:*
  '@claude-zen/operations': workspace:*

overrides:
  '@anthropic-ai/claude-code@<0.2.111': '>=0.2.111'
  '@anthropic-ai/claude-code@<1.0.20': '>=1.0.20'
  '@anthropic-ai/claude-code@<1.0.4': '>=1.0.4'
  ajv@<6.12.3: '>=6.12.3'
  axios@<0.30.0: '>=0.30.0'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  cookie@<0.7.0: '>=0.7.0'
  debug@>=4.0.0 <4.3.1: '>=4.3.1'
  ejs@<3.1.10: '>=3.1.10'
  ejs@<3.1.7: '>=3.1.7'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  hawk@<9.0.1: '>=9.0.1'
  highlight.js@>=9.0.0 <10.4.1: '>=10.4.1'
  hoek@<4.2.1: '>=4.2.1'
  lodash@<4.17.11: '>=4.17.11'
  lodash@<4.17.12: '>=4.17.12'
  lodash@<4.17.21: '>=4.17.21'
  lodash@<4.17.5: '>=4.17.5'
  lodash@>=3.7.0 <4.17.19: '>=4.17.19'
  markdown-it@<12.3.2: '>=12.3.2'
  marked@<4.0.10: '>=4.0.10'
  marked@>=0.3.14 <0.6.2: '>=0.6.2'
  on-headers@<1.1.0: '>=1.1.0'
  slug@<=0.9.1: '>=0.9.2'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
