packages:
  - apps/*
  - packages/foundation
  - packages/strategic-facades/*
  - packages/implementation-packages/*
  - '!apps/*-backup'

overrides:
  # Strategic facades (4 interface packages)
  '@claude-zen/infrastructure': link:packages/strategic-facades/infrastructure
  '@claude-zen/intelligence': link:packages/strategic-facades/intelligence
  '@claude-zen/enterprise': link:packages/strategic-facades/enterprise
  '@claude-zen/operations': link:packages/strategic-facades/operations
  
  # Updated implementation package paths
  '@claude-zen/agui': link:packages/implementation-packages/agui
  '@claude-zen/brain': link:packages/implementation-packages/brain
  '@claude-zen/database': link:packages/implementation-packages/database
  '@claude-zen/memory': link:packages/implementation-packages/memory
  '@claude-zen/kanban': link:packages/implementation-packages/kanban
  '@claude-zen/telemetry': link:packages/implementation-packages/telemetry
  '@claude-zen/system-monitoring': link:packages/implementation-packages/system-monitoring
  '@claude-zen/agent-monitoring': link:packages/implementation-packages/agent-monitoring
  '@claude-zen/neural-ml': link:packages/implementation-packages/neural-ml
  '@claude-zen/workflows': link:packages/implementation-packages/workflows
  '@claude-zen/teamwork': link:packages/implementation-packages/teamwork
  '@claude-zen/knowledge': link:packages/implementation-packages/knowledge
  '@claude-zen/event-system': link:packages/implementation-packages/event-system
  '@claude-zen/ai-safety': link:packages/implementation-packages/ai-safety
  '@claude-zen/load-balancing': link:packages/implementation-packages/load-balancing
  '@claude-zen/otel-collector': link:packages/implementation-packages/otel-collector
