packages:
  # Apps
  - 'apps/*'

  # New packages structure - 5-tier architecture
  - 'packages/core/*'
  # Temporarily excluded load-balancing package due to 300+ errors
  # To re-enable: uncomment the wildcard and remove explicit list
  # - 'packages/services/*'
  - 'packages/tools/*'
  - 'packages/integrations/*'
  - 'packages/services/*'