packages:
  - apps/*
  - packages/foundation
  - packages/llm-providers
  - packages/development
  - packages/enterprise
  - packages/infrastructure
  - packages/intelligence
  - packages/operations
  - packages/repo-analyzer
  - packages/language-parsers
  - packages/ai-linter
  - packages/implementation-packages/*
  - '!apps/*-backup'

catalog:
  # Tier 1: Public API - Core foundation and strategic facades only
  '@claude-zen/foundation': 'workspace:*'
  '@claude-zen/llm-providers': 'workspace:*'
  
  # Strategic facades (5 interface packages) - ONLY public packages
  '@claude-zen/infrastructure': 'workspace:*'
  '@claude-zen/intelligence': 'workspace:*'
  '@claude-zen/enterprise': 'workspace:*'
  '@claude-zen/operations': 'workspace:*'
  '@claude-zen/development': 'workspace:*'
  
# Development support packages moved to Tier 2 - accessed via @claude-zen/development facade
  # '@claude-zen/repo-analyzer': 'workspace:*'     # Now internal - use development.getRepoAnalyzer()
  # '@claude-zen/language-parsers': 'workspace:*'  # Now internal - use development.getLanguageParsers()  
  # '@claude-zen/ai-linter': 'workspace:*'          # Now internal - use development.getAILinter()
  
  # NOTE: All implementation packages removed from catalog - they are internal only
  # Tier 2 & 3 packages are private and accessed only via strategic facades
