packages:
  # Apps
  - 'apps/*'
  
  # New packages structure - 5-tier architecture
  - 'packages/core/*'
  - 'packages/services/*'
  - 'packages/tools/*'
  - 'packages/integrations/*'
  
  # Old packages (during migration)
  - 'packages-old/implementation/*'
  - 'packages-old/enterprise/*'