#!/bin/bash

# GitHub Projects Setup Script
# Run this script to help set up the 4 main GitHub Projects

echo "🚀 Claude Code Zen - GitHub Projects Setup Guide"
echo "================================================"
echo ""

echo "📋 STEP 1: Create GitHub Projects (Manual via Web Interface)"
echo "-----------------------------------------------------------"
echo "Go to: https://github.com/mikkihugo/zenflow/projects"
echo ""
echo "Create these 4 projects:"
echo "1. 🧠 Neural AI Platform (Zen Neural Stack)"
echo "   - Description: Strategic independence & 10-100x performance improvements"
echo "   - Template: Table"
echo ""
echo "2. 🔍 Auto-Discovery & Domain Intelligence" 
echo "   - Description: Zero-manual-initialization with 90%+ accuracy"
echo "   - Template: Table"
echo ""
echo "3. 🏢 Enterprise Platform & SAFe Integration"
echo "   - Description: Production-ready with SOC2 compliance"
echo "   - Template: Table"
echo ""
echo "4. 🧪 Testing, Validation & Quality"
echo "   - Description: Cross-cutting quality assurance"
echo "   - Template: Table"
echo ""

echo "📝 STEP 2: Create Project Columns/Fields"
echo "----------------------------------------"
echo "For each project, add these columns:"
echo "- 📋 Backlog (New issues)"
echo "- 🔄 In Progress (Active development)"
echo "- 👥 In Review (Code review/testing)"
echo "- ✅ Done (Completed)"
echo ""
echo "Add these custom fields:"
echo "- Priority: Single select (Critical, High, Medium, Low)"
echo "- SPARC Phase: Single select (Specification, Planning, Analysis, Research, Completion)"
echo "- Team: Single select (Neural, Discovery, Enterprise, Quality, DevOps)"
echo "- Sprint: Text (e.g., 'Sprint 1', 'Sprint 2')"
echo ""

echo "🏷️ STEP 3: Create GitHub Labels"
echo "--------------------------------"
echo "Go to: https://github.com/mikkihugo/zenflow/labels"
echo ""
echo "Create these labels:"
echo "Epic & Priority Labels:"
echo "- epic (color: #d73a4a)"
echo "- feature (color: #0075ca)" 
echo "- critical (color: #b60205)"
echo "- high-priority (color: #d93f0b)"
echo "- medium-priority (color: #fbca04)"
echo "- low-priority (color: #0e8a16)"
echo ""
echo "Domain Labels:"
echo "- neural-platform (color: #5319e7)"
echo "- zen-neural-stack (color: #7057ff)"
echo "- auto-discovery (color: #1d76db)"
echo "- domain-intelligence (color: #0969da)"
echo "- enterprise-platform (color: #bf8700)"
echo "- safe-framework (color: #d4801f)"
echo "- production (color: #8b5cf6)"
echo ""
echo "SPARC Phase Labels:"
echo "- sparc-specification (color: #f85149)"
echo "- sparc-planning (color: #ff8c00)"
echo "- sparc-analysis (color: #ffd700)"
echo "- sparc-research (color: #32cd32)"
echo "- sparc-completion (color: #00ced1)"
echo ""

echo "📅 STEP 4: Create Milestones"
echo "----------------------------"
echo "Go to: https://github.com/mikkihugo/zenflow/milestones"
echo ""
echo "Create these milestones:"
echo "Q4 2024 Milestones:"
echo "- Neural Platform Strategic Independence (Week 0)"
echo "- Core Architecture Migration (Week 4)"
echo "- Discovery Neural Enhancement (Week 4)"
echo "- Enterprise Security Implementation (Week 4)"
echo ""
echo "Q1 2025 Milestones:"
echo "- Universal Deployment Ready (Week 8)"
echo "- Discovery Learning & Memory (Week 8)"
echo "- Enterprise Scale & Performance (Week 8)"
echo "- Intelligent Orchestration Complete (Week 12)"
echo ""
echo "Q2 2025 Milestones:"
echo "- Discovery Production Validation (Week 12)"
echo "- Enterprise Advanced Analytics (Week 12)"
echo "- System Integration Validation (Week 16)"
echo "- Production Excellence Achievement (Week 20)"
echo ""

echo "🎯 STEP 5: Create Initial Epic Issues"
echo "-------------------------------------"
echo "Use the issue templates in .github/ISSUE_TEMPLATE/ to create epic issues:"
echo ""
echo "Neural AI Platform Epics:"
echo "- [NEURAL] Strategic Independence & Fork Execution"
echo "- [NEURAL] Core Neural Architecture Migration"
echo "- [NEURAL] Universal Deployment (WASM/WebGPU)"
echo "- [NEURAL] DAA Intelligent Orchestration"
echo ""
echo "Auto-Discovery & Domain Intelligence Epics:"
echo "- [DISCOVERY] Neural-Enhanced Discovery"
echo "- [DISCOVERY] Learning & Memory Integration"
echo "- [DISCOVERY] Production Validation"
echo "- [DISCOVERY] CLI Integration"
echo ""
echo "Enterprise Platform & SAFe Integration Epics:"
echo "- [ENTERPRISE] Security & Compliance"
echo "- [ENTERPRISE] Scale & High-Availability"
echo "- [ENTERPRISE] Advanced Analytics"
echo "- [ENTERPRISE] Ecosystem Integration"
echo ""
echo "Testing, Validation & Quality Epics:"
echo "- [QUALITY] Neural Platform Testing"
echo "- [QUALITY] Discovery System Testing"
echo "- [QUALITY] Enterprise Platform Testing"
echo "- [QUALITY] Integration Testing"
echo ""

echo "📊 STEP 6: Set up Project Automation"
echo "------------------------------------"
echo "In each project, set up these automations:"
echo "- Auto-add items: When issues/PRs are labeled with project tags"
echo "- Auto-move items: Move to 'In Progress' when status changes to 'In Progress'"
echo "- Auto-move items: Move to 'Done' when issues are closed"
echo "- Auto-archive: Archive items after 30 days in 'Done'"
echo ""

echo "✅ STEP 7: Initial Project Population"
echo "-------------------------------------"
echo "1. Create epic issues using templates"
echo "2. Assign epics to appropriate projects"
echo "3. Set milestone and priority for each epic"
echo "4. Add initial team assignments"
echo "5. Create first sprint's detailed issues"
echo ""

echo "🎉 PROJECT SETUP COMPLETE!"
echo "=========================="
echo ""
echo "Next steps:"
echo "1. Follow this guide to set up all 4 GitHub Projects"
echo "2. Create epic issues using the templates"
echo "3. Assign team members to projects"
echo "4. Begin Sprint 1 planning"
echo ""
echo "📚 Reference Files:"
echo "- GITHUB_PROJECTS_ROADMAP.md - Complete implementation guide"
echo "- github-project-plan.md - Detailed analysis and planning"
echo "- .github/ISSUE_TEMPLATE/ - Epic issue templates"
echo ""
echo "🎯 Success Metrics:"
echo "- 2,872+ lines of archived content → Actionable GitHub issues"
echo "- Clear SAFe 6.0 and SPARC methodology integration"
echo "- Measurable progress tracking with defined KPIs"
echo ""