/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  entryPoints: ['src'],
  out: 'docs/api',
  name: 'Claude Code Zen',

  // Basic settings
  readme: 'README.md',
  includeVersion: true,
  sort: ['source-order'],

  // Theme and output
  theme: 'default',
  plugin: ['typedoc-plugin-missing-exports'],

  // Include everything
  excludeExternals: false,
  excludeNotDocumented: false,
  excludePrivate: false,
  excludeProtected: false,

  // TypeScript settings
  tsconfig: 'tsconfig.json',
  emit: 'docs',

  // Navigation
  navigation: {
    includeCategories: true,
    includeGroups: true,
  },

  // Search
  searchInComments: true,
  searchInDocuments: true,

  // Validation - disable warnings for unknown tags
  validation: {
    notExported: true,
    invalidLink: true,
    notDocumented: false,
  },

  // Custom block tags to suppress warnings
  blockTags: [
    '@param',
    '@returns',
    '@throws',
    '@example',
    '@deprecated',
    '@since',
    '@author',
    '@see',
    '@file',
    '@fileoverview',
    '@usage',
    '@autoGenerated',
    '@importedBy',
    '@constant',
    '@implements',
    '@version',
    '@swagger',
  ],

  // Inline tags
  inlineTags: ['@link', '@linkcode', '@linkplain'],

  // Suppress specific warnings
  logLevel: 'Warn',
  treatWarningsAsErrors: false,
};
