/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  entryPoints: [
    'src/coordination/types.ts',
    'src/core/types.ts',
    'src/core/type-guards.ts',
    'src/types/shared-types.ts',
    'src/utils/index.ts',
  ],
  out: 'docs/api',
  name: 'Claude Code Zen - Core Documentation',

  // Basic settings
  readme: 'README.md',
  includeVersion: true,
  sort: ['source-order'],

  // Theme and output
  theme: 'default',
  plugin: ['typedoc-plugin-missing-exports'],

  // Include everything but be selective with entry points
  excludeExternals: true,
  excludeNotDocumented: false,
  excludePrivate: false,
  excludeProtected: false,

  // Custom block tags to suppress warnings
  blockTags: [
    '@param',
    '@returns',
    '@throws',
    '@example',
    '@deprecated',
    '@since',
    '@author',
    '@see',
    '@file',
    '@fileoverview',
    '@usage',
    '@autoGenerated',
    '@importedBy',
    '@constant',
    '@implements',
    '@version',
    '@swagger',
  ],

  // Suppress specific warnings
  logLevel: 'Info',
  treatWarningsAsErrors: false,
};
