/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  entryPoints: ['src'],
  out: 'docs/api',
  name: 'Claude Code Zen - Complete API Documentation',

  // Basic settings
  readme: 'README.md',
  includeVersion: true,
  sort: ['source-order'],

  // Theme and output
  theme: 'default',
  plugin: ['typedoc-plugin-missing-exports'],

  // Include as much as possible
  excludeExternals: true,
  excludeNotDocumented: false,
  excludePrivate: false,
  excludeProtected: false,

  // Skip problematic patterns that cause infinite loops or major errors
  exclude: [
    '**/node_modules/**/*',
    '**/dist/**/*',
    '**/coverage/**/*',
    '**/*.test.ts',
    '**/*.spec.ts',
    '**/tests/**/*',
    '**/__tests__/**/*',
    '**/test-utils/**/*',
    '**/test-*',
    // Skip specific problematic files that have many errors
    '**/client-integration-tests.ts',
    '**/mcp-client-integration-tests.ts',
    '**/unified-client-integration.ts',
  ],

  // Complete AI-friendly JSDoc tags
  blockTags: [
    '@param',
    '@returns',
    '@throws',
    '@example',
    '@deprecated',
    '@since',
    '@author',
    '@see',
    '@file',
    '@fileoverview',
    '@usage',
    '@autoGenerated',
    '@importedBy',
    '@constant',
    '@implements',
    '@version',
    '@swagger',
    '@internal',
    '@beta',
    '@alpha',
    '@public',
    '@private',
    '@protected',
    '@readonly',
    '@static',
    '@template',
    '@augments',
    '@description',
    '@property',
    '@fires',
    '@emits',
    '@listens',
    '@namespace',
    '@memberof',
    '@override',
    '@abstract',
    '@virtual',
    '@inner',
    '@instance',
    '@global',
  ],

  // Handle errors gracefully
  logLevel: 'Warn',
  treatWarningsAsErrors: false,
  skipErrorChecking: true,

  // Performance settings for large codebase
  preserveWatchOutput: false,
  pretty: true,

  // Navigation and organization
  navigation: {
    includeCategories: true,
    includeGroups: true,
    includeFolders: true,
  },

  // Search functionality
  searchInComments: true,

  // Better categorization
  categorizeByGroup: true,
  defaultCategory: 'Other',

  // Output settings
  cleanOutputDir: true,
  githubPages: false,
};
