apiVersion: v2
name: vision-to-code
description: Helm chart for Vision-to-Code system deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/ruvnet/claude-code-flow
maintainers:
  - name: DevOps Team
    email: devops@vision-to-code.com
sources:
  - https://github.com/ruvnet/claude-code-flow
keywords:
  - vision-to-code
  - ai
  - microservices
  - elixir
  - kubernetes
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
  - name: grafana
    version: "7.0.8"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.enabled
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled