[package]
name = "quality-gates"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["claude-code-zen Team"]
description = "Quality gate enforcement with Oxlint and ESLint integration"

[dependencies]
# Workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["process", "io-util"] }

# Quality gate dependencies
regex = { workspace = true }
tempfile = { workspace = true }

[features]
default = ["oxlint", "eslint"]
oxlint = []
eslint = []

[lib]
name = "quality_gates"
crate-type = ["rlib"]
