[workspace]
members = [
    "crates/code-analyzer-core",
    "crates/quality-gates",
    "crates/sparc-methodology",
    "crates/safe-integration",
]
resolver = "2"

[workspace.dependencies]
# Core Rust dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }

# File system and path handling
walkdir = "2.5"
ignore = "0.4"
glob = "0.3"

# Text processing
regex = "1.10"
aho-corasick = "1.1"
memchr = "2.7"

# AST parsing
tree-sitter = "0.22"
tree-sitter-rust = "0.21"
tree-sitter-typescript = "0.21"
tree-sitter-javascript = "0.21"
tree-sitter-python = "0.21"
tree-sitter-go = "0.21"

# Parallel processing
rayon = "1.8"

# Collections and data structures
indexmap = { version = "2.2", features = ["serde"] }
dashmap = "7.0.0-rc2"

# Database dependencies (for code analysis storage)
rusqlite = "0.32"
tempfile = "3.0"
chrono = { version = "0.4", features = ["serde"] }

# ML and analysis
levenshtein = "1.0"
md5 = "0.7"

# ML Dependencies - Production Ready
burn = { version = "0.13", features = ["train", "autodiff", "std"] }
linfa = "0.8"
linfa-clustering = "0.8"
linfa-preprocessing = "0.8"
statrs = "0.17"

# Development dependencies
criterion = "0.5"
tokio-test = "0.4"

# Additional dependencies
uuid = { version = "1.8", features = ["v4"] }
metrics = "0.21"
tracing = "0.1"
num_cpus = "1.16"
serde_yaml = "0.9"
notify = "6.1"
