[package]
name = "sparc-methodology"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["claude-code-zen Team"]
description = "SPARC 5-phase development methodology engine"

[dependencies]
# Workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true, features = ["serde"] }

# SPARC methodology dependencies
uuid = { version = "1.0", features = ["v4", "serde"] }
dashmap = { workspace = true }

[lib]
name = "sparc_methodology"
crate-type = ["rlib"]
