#!/usr/bin/env bash

# Simple Claude Lint & Fix - Uses claude -p with lint prompt, commits and pushes

set -euo pipefail

echo "[SIMPLE-CLAUDE-LINT] Starting..."

# Simple lint prompt for Claude
LINT_PROMPT="Fix all TypeScript errors, type issues, unused imports, and code quality problems in this codebase. Focus on making it compile and removing all linting errors. Make production-ready improvements."

echo "[LINT] Running claude -p with lint prompt..."

# Run claude with prompt  
claude -p "$LINT_PROMPT"

echo "[COMMIT] Committing changes..."

# Check if we have changes to commit
if git diff --quiet && git diff --cached --quiet; then
    echo "[NO-CHANGES] No changes to commit"
    exit 0
fi

# Stage all changes
git add -A

# Commit with timestamp
COMMIT_MSG="Auto-lint: Claude fixes $(date '+%Y-%m-%d %H:%M:%S')

Applied comprehensive linting fixes:
- TypeScript errors resolved
- Code quality improvements  
- Unused imports removed
- Production-ready optimizations

Generated by claude -p lint command"

git commit -m "$COMMIT_MSG"

echo "[PUSH] Pushing to remote..."

# Push to current branch
if git push 2>/dev/null; then
    echo "[SUCCESS] Changes committed and pushed!"
else
    echo "[WARNING] Could not push - changes committed locally"
fi

echo "[DONE] Simple Claude lint complete"