# Tarpaulin configuration for comprehensive test coverage

[default]
# Coverage options
branch = true
count = true
line = true
verbose = true
all-features = true
workspace = true
timeout = "900"  # 15 minutes for comprehensive tests
exclude-files = ["*/tests/*", "*/benches/*", "*/examples/*", "*/test_*.rs"]
ignore-panics = true
ignored = ["build.rs", "src/bin/*"]

# Output formats
out = ["Html", "Xml", "Lcov", "Json"]
output-dir = "target/coverage"

# Test options
test-threads = 4
release = false
no-run = false

# Coverage thresholds - targeting 90%
fail-under = 80.0
target = 90.0

# Include specific test patterns
include = [
    "src/**/*.rs"
]

# Exclude specific patterns
exclude = [
    "tests/**/*",
    "benches/**/*", 
    "examples/**/*",
    "**/test_utils.rs",
    "**/mock_*.rs"
]

[report]
# Coveralls integration
coveralls = "${COVERALLS_REPO_TOKEN}"

# Codecov integration  
codecov = "${CODECOV_TOKEN}"

[html]
# HTML report configuration
title = "CUDA-Rust-WASM Coverage Report"
description = "Comprehensive test coverage for the CUDA to Rust/WASM transpiler"

[env]
# Environment variables for testing
RUST_BACKTRACE = "1"
RUST_LOG = "debug"
PROPTEST_CASES = "1000"
PROPTEST_MAX_SHRINK_ITERS = "1000"

# Performance and stress test configurations
[profile.test]
# Exclude slow tests by default, include with --features slow-tests
default-features = false
features = ["default"]

[profile.comprehensive]
# Full test suite including slow tests
features = ["default", "slow-tests", "stress-tests"]
timeout = "1800"  # 30 minutes
test-threads = 2