name: Copilot Autonomous Task
description: Task for GitHub Copilot Coding Agent following domain-driven patterns
title: "[COPILOT] "
labels: ["copilot-autonomous", "enhancement"]
assignees: ["copilot"]

body:
  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Clear, specific task for autonomous completion
      placeholder: |
        Implement feature X following domain-driven architecture...
        
        Requirements:
        - Use existing AgentType from src/types/agent-types.ts (147+ available)
        - Follow domain structure in src/
        - Add tests using hybrid-tdd approach
        - Maintain performance requirements
    validations:
      required: true
      
  - type: dropdown
    id: domain
    attributes:
      label: Primary Domain
      description: Which domain will this primarily affect?
      options:
        - "coordination"

        - "neural"

        - "interfaces"

        - "memory"

        - "database"

        - "core"

        - "intelligence"

        - "workflows"

    validations:
      required: true
      
  - type: checkboxes
    id: architecture-compliance
    attributes:
      label: Architecture Requirements
      description: Key constraints for claude-code-zen
      options:
        - label: "Use existing 147+ agent types (not generic implementations)"
        - label: "Follow domain-driven with domain boundaries"
        - label: "Use hybrid-tdd (70% London, 30% Classical)"
        - label: "Integrate with MCP servers (port 3000)"

        - label: "Use WASM for performance-critical neural code"

        
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we validate completion?
      placeholder: |
        - [ ] Implementation follows domain-driven patterns
        - [ ] Tests pass (70% London + 30% Classical)
        - [ ] Performance benchmarks maintained
        - [ ] Architecture validation passes
        - [ ] No breaking changes to existing systems