# WASM configuration for core swarm module
[build]
target = "wasm32-unknown-unknown"
profile = "release"

[features]
default = ["simd", "parallel"]
simd = true
parallel = true
optimize = true

[optimization]
# Size optimization settings
opt-level = "z"          # Optimize for size
lto = true              # Link-time optimization
codegen-units = 1       # Single codegen unit for better optimization

[memory]
# Memory configuration for swarm operations
initial_pages = 64      # 4MB initial memory
maximum_pages = 1024    # 64MB maximum memory
stack_size = 1048576    # 1MB stack

[wasm-opt]
# wasm-opt optimization flags
flags = [
    "-Oz",              # Optimize for size
    "--enable-simd",    # Enable SIMD instructions
    "--enable-bulk-memory",
    "--enable-threads",
    "--converge",       # Run until convergence
]