# WASM configuration for forecasting models
[build]
target = "wasm32-unknown-unknown"
profile = "release"

[features]
default = ["simd", "parallel", "neuro-divergent"]
simd = true
parallel = true
optimize = true
neuro-divergent = true

[optimization]
# Balanced optimization for forecasting
opt-level = 2           # Balanced speed/size
lto = true              # Link-time optimization
codegen-units = 1       # Single codegen unit

[memory]
# Memory configuration for time series data
initial_pages = 128     # 8MB initial memory
maximum_pages = 2048    # 128MB maximum memory
stack_size = 1572864    # 1.5MB stack

[wasm-opt]
# wasm-opt optimization flags for forecasting
flags = [
    "-O2",              # Balanced optimization
    "--enable-simd",    # SIMD for time series ops
    "--enable-bulk-memory",
    "--enable-threads",
    "--enable-nontrapping-float-to-int",
    "--converge",
]