# WASM configuration for neural network module
[build]
target = "wasm32-unknown-unknown"
profile = "release"

[features]
default = ["simd", "parallel", "ruv-fann"]
simd = true
parallel = true
optimize = true
ruv-fann = true

[optimization]
# Performance optimization for neural operations
opt-level = 3           # Optimize for speed
lto = true              # Link-time optimization
codegen-units = 1       # Single codegen unit

[memory]
# Memory configuration for neural networks
initial_pages = 256     # 16MB initial memory
maximum_pages = 4096    # 256MB maximum memory
stack_size = 2097152    # 2MB stack for deep networks

[wasm-opt]
# wasm-opt optimization flags for neural operations
flags = [
    "-O3",              # Optimize for speed
    "--enable-simd",    # SIMD for vector operations
    "--enable-bulk-memory",
    "--enable-threads",
    "--enable-nontrapping-float-to-int",
    "--converge",
]