[package]
name = "fact-tools"
version = "1.1.0"
authors = ["mikkihugo"]
edition = "2021"
description = "FACT (Fast Augmented Context Tools) - High-performance context processing engine for AI applications"
homepage = "https://github.com/mikkihugo/claude-code-zen"
repository = "https://github.com/mikkihugo/claude-code-zen"
license = "MIT"
readme = "README.md"
keywords = ["fact", "cognitive", "ai", "cache", "performance"]
categories = ["algorithms", "caching", "command-line-utilities", "web-programming"]

[lib]
name = "fact_tools"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "fact-tools"
path = "src/bin/main.rs"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ahash = "0.8"
smallvec = "1.13"
parking_lot = "0.12"
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.16"
wasm-bindgen = "0.2"

# CLI dependencies
clap = { version = "4.4", features = ["derive", "cargo", "env", "unicode"] }
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"

# Logging and diagnostics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Performance monitoring
dashmap = "5.5"
crossbeam = "0.8"
rayon = "1.8"

# Simple storage dependencies - using foundation pattern
regex = "1.10"
async-trait = "0.1"
log = "0.4"

# Use local storage, not external databases
bincode = "1.3"
dirs = "5.0"

# Optional dependencies for github and auto features
notify = { version = "6.0", optional = true }
octocrab = { version = "0.38", optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"
tempfile = "3.8"
mockall = "0.12"

[features]
default = ["std"]
std = []
github = ["dep:octocrab", "dep:reqwest"]
github-graphql = ["github"]
auto = ["dep:notify"]
orchestration = []
storage = []

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1


[[example]]
name = "basic"
path = "examples/basic.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]