[package]
name = "code-mesh-tui"
version = "0.1.0"
authors = ["claude-code-zen Team"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Interactive Terminal User Interface for the Code-Mesh distributed swarm intelligence system"
homepage = "https://github.com/ruvnet/code-mesh"
repository = "https://github.com/ruvnet/code-mesh"
documentation = "https://docs.rs/code-mesh-tui"
readme = "README.md"
keywords = ["tui", "terminal", "swarm", "visualization", "monitoring"]
categories = ["command-line-utilities", "visualization", "development-tools"]

[dependencies]
# Core dependencies
code-mesh-core = { version = "0.1.0", path = "../code-mesh-core" }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }

# TUI dependencies - align versions to fix conflicts
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
tui-textarea = "0.7"
tui-input = "0.14"

# Text processing and rendering
syntect = "5.1"
pulldown-cmark = "0.9"
unicode-width = "0.1"
unicode-segmentation = "1.10"

# Color and styling
owo-colors = "4.0"

# Event handling
futures = "0.3"
futures-util = "0.3"

# File and path utilities
dirs = "5.0"
walkdir = "2.4"

# Date/time
chrono = { version = "0.4", features = ["serde"] }

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
[features]
default = ["std", "auto-optimization"]
std = []
auto-optimization = []
