#!/usr/bin/env node

/**
 * Complete Test for Maestro Steering
 * Tests comprehensive steering document workflow
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

// Complete steering test
async function testMaestroSteeringComplete(): Promise<void> {
  interface SteeringTemplate {
    name: string;
    focus: string;
    sections: string[];
  }

  class TestSteeringComplete {
    private templates: SteeringTemplate[] = [
      {
        name: 'technical',
        focus: 'technical implementation',
        sections: ['Architecture', 'Implementation', 'Testing'],
      },
      {
        name: 'product',
        focus: 'product requirements',
        sections: ['Requirements', 'User Stories', 'Acceptance Criteria'],
      },
    ];

    async createComprehensiveSteeringDocuments(feature: string): Promise<void> {
      for (const template of this.templates) {
        await this.createSteeringFromTemplate(feature, template);
      }
    }

    private async createSteeringFromTemplate(
      feature: string,
      template: SteeringTemplate,
    ): Promise<void> {
      const steeringDir = join(process.cwd(), 'docs', 'maestro', 'steering', template.name);
      await mkdir(steeringDir, { recursive: true });

      const steeringContent = `# ${feature} Steering Document (${template.name})

## Overview
This steering document focuses on ${template.focus} for **${feature}**.

## Sections
${template.sections
  .map(
    (section) => `### ${section}
      - Guidelines for ${section.toLowerCase()}`,
  )
  .join('\n')}

## Decision Framework
- Review existing patterns
- Consider system impact
- Document rationale

*Generated by Complete Steering Test*
`;

      const fileName = `${feature.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${template.name}-steering.md`;
      const filePath = join(steeringDir, fileName);
      await writeFile(filePath, steeringContent);
    }

    async runCompleteSteeringTest(): Promise<void> {
      const testFeatures = ['user-authentication', 'data-processing', 'api-gateway'];

      for (const feature of testFeatures) {
        await this.createComprehensiveSteeringDocuments(feature);

        // Brief pause between features
        await new Promise((resolve) => setTimeout(resolve, 150));
      }

      const _totalDocs = testFeatures.length * this.templates.length;
    }
  }

  try {
    const steering = new TestSteeringComplete();
    await steering.runCompleteSteeringTest();
  } catch (error) {
    console.error(
      `
      ❌ Complete steering test failed:`,
      error,
    );
    process.exit(1);
  }
}

// Run the test
if (import.meta.url === `file://${process.argv[1]}`) {
  testMaestroSteeringComplete().catch((error) => {
    console.error('Test execution failed:', error);
    process.exit(1);
  });
}
