/** 
 * @file Auto-generated type definitions for agent
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY
 */

export interface GlobalAgentInfo {
  id: string;
  type: string;
  status: 'active' | 'inactive' | 'error';
  capabilities: string[];
  metrics: {
    tasksCompleted: number;
    averageResponseTime: number;
    errorRate: number;
  };
}

// Convenience exports
export type {
  GlobalAgentInfo,
};
