/** 
 * @file Auto-generated type definitions for knowledge
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY
 */

export interface KnowledgeResult {
  id: string;
  content: string;
  score: number;
  metadata: Record<string, unknown>;
}

export interface FACTKnowledgeEntry {
  id: string;
  content: string;
  score: number;
  metadata: Record<string, unknown>;
}

// Convenience exports
export type {
  KnowledgeResult,
  FACTKnowledgeEntry,
};
