/** 
 * @file Auto-generated type definitions for mcp
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY
 */

import type { MCPTool } from './shared-types';

export interface advancedMCPToolsManager {
  registerTool(tool: MCPTool): void;
  getTool(name: string): MCPTool | undefined;
  listTools(): MCPTool[];
  executeTool(name: string, args: unknown): Promise<unknown>;
}

// Convenience exports
export type {
  advancedMCPToolsManager,
};
