/**
 * @file Auto-generated type definitions for mcp
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY.
 */

// Define MCPTool interface locally since it's not in shared-types
export interface MCPTool {
  name: string;
  description?: string;
  parameters?: Record<string, unknown>;
}

export interface advancedMCPToolsManager {
  registerTool(tool: MCPTool): void;
  getTool(name: string): MCPTool | undefined;
  listTools(): MCPTool[];
  executeTool(name: string, args: unknown): Promise<unknown>;
}

// Convenience exports - advancedMCPToolsManager already exported above
