/**
 * @file Auto-generated type definitions for neural
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY.
 */

export class NeuralError extends Error {
  constructor(
    message: string,
    public readonly code: string = 'NEURAL_ERROR',
    public readonly details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'NeuralError';
  }
}

// Class is already exported above - no need for type export
