/**
 * @file Auto-generated type definitions for neural
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY.
 */
export declare class NeuralError extends Error {
    readonly code: string;
    readonly details?: Record<string, unknown> | undefined;
    constructor(message: string, code?: string, details?: Record<string, unknown> | undefined);
}
//# sourceMappingURL=neural-types.d.ts.map