/**
 * @file Auto-generated type definitions for services
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY.
 */

export class ServiceOperationError extends Error {
  constructor(
    message: string,
    public readonly service: string,
    public readonly operation?: string,
  ) {
    super(message);
    this.name = 'ServiceOperationError';
  }
}

export interface ServiceConfigFactory {
  create<T>(config: unknown): T;
  validate(config: unknown): boolean;
}

export class ServiceTimeoutError extends Error {
  constructor(
    message: string,
    public readonly service: string,
    public readonly operation?: string,
  ) {
    super(message);
    this.name = 'ServiceTimeoutError';
  }
}

// Classes are already exported above - no need for type exports
