/**
 * @file Global singleton instances
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY.
 */

import type { ClientManagerHelpers } from './client-types.ts';

// Global singleton instances (to be implemented by actual services)
export declare const globalClientManager: {
  http: ClientManagerHelpers;
  websocket: ClientManagerHelpers;
  mcp: ClientManagerHelpers;
};

export declare const globalUSLFactory: {
  createService<T>(type: string, config: unknown): T;
  getService<T>(id: string): T | undefined;
};

export declare const globalServiceRegistry: {
  register<T>(id: string, service: T): void;
  get<T>(id: string): T | undefined;
  list(): string[];
};

// Singletons are already exported above - no need for re-export
