/** 
 * @file Auto-generated type definitions for workflow
 * Generated by fix-missing-types.js - DO NOT EDIT MANUALLY
 */

export interface WorkflowContext {
  id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  metadata?: Record<string, unknown>;
  timestamp: Date;
}

export interface WorkflowState {
  id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  metadata?: Record<string, unknown>;
  timestamp: Date;
}

export interface WorkflowEngineConfig {
  id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  metadata?: Record<string, unknown>;
  timestamp: Date;
}

export interface ExecutionPlan {
  id: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  metadata?: Record<string, unknown>;
  timestamp: Date;
}

// Convenience exports
export type {
  WorkflowContext,
  WorkflowState,
  WorkflowEngineConfig,
  ExecutionPlan,
};
