/**
 * @fileoverview Contains shared, simple data types used across multiple interfaces.
 *
 * This file is for plain data structures (like `type` or `interface` definitions
 * with only properties) that need to be passed between different parts of the.
 * system or used by multiple interfaces.
 *
 * For example, a `SystemStatus` object might be generated by the core system.
 * and displayed by both the web and terminal interfaces.
 */

/**
 * Represents the overall health and status of a system component.
 */
export interface ComponentStatus {
  name: string;
  health: 'healthy' | 'degraded' | 'unhealthy';
  message?: string;
}

/**
 * Configuration for a web server instance.
 * Used by both the `web` and `terminal` (e.g., for a local dashboard) interfaces.
 */
export interface WebServerConfig {
  port: number;
  host: string;
  enableHttps: boolean;
  theme: 'dark' | 'light';
}

/**
 * Configuration for user sessions.
 */
export interface SessionConfig {
  secret: string;
  timeout: number; // in minutes
}

/**
 * A shared configuration object for web-based interfaces.
 */
export interface WebConfig {
  server: WebServerConfig;
  session: SessionConfig;
}
