/**
 * @file Claude-Zen Batch Operations Example
 * Demonstrates the "1 MESSAGE = ALL OPERATIONS" principle with practical examples
 */

import { createBatchSystem } from '../coordination/batch';
import {
  createClaudeZenPattern,
  projectInitBatchTool,
} from '../coordination/swarm/mcp/batch-tools';

/**
 * Example 1: Basic Claude-Zen Pattern
 * This demonstrates the core "1 MESSAGE = ALL OPERATIONS" principle
 */
export async function exampleBasicClaudeZenPattern() {
  // Create the classic claude-zen pattern operations
  const operations = createClaudeZenPattern({
    swarmTopology: 'mesh',
    maxAgents: 6,
    agentTypes: ['researcher', 'coder', 'analyst'],
    projectStructure: ['app', 'app/src', 'app/tests', 'app/docs'],
    files: [
      {
        path: 'app/package.json',
        content: JSON.stringify(
          {
            name: 'claude-zen-example',
            version: '1.0.0',
            description: 'Example project using claude-zen batch operations',
            scripts: {
              build: 'tsc',
              test: 'jest',
              dev: 'npm run build && node dist/index.js',
            },
          },
          null,
          2
        ),
      },
      {
        path: 'app/README.md',
        content: `# Claude-zen Example

This project demonstrates the power of claude-zen's batch operations:

## Benefits Achieved
- 🚀 2.8-4.4x speed improvement through concurrent execution
- 🎯 32.3% token reduction through batch optimization  
- 🤖 Coordinated swarm intelligence with multiple agent types

## Architecture
- **Swarm Topology**: Mesh network for optimal coordination
- **Agents**: Researcher, Coder, Analyst working in parallel
- **Operations**: All project setup in a single batch execution

Generated by claude-zen batch operations ⚡
`,
      },
    ],
  });

  // Execute using the batch system
  const batchSystem = createBatchSystem();
  const result = await batchSystem.executeBatchWorkflow(operations);

  return result;
}

/**
 * Example 2: Project Initialization via MCP
 * Shows how to use the MCP tools for project setup
 */
export async function exampleProjectInitialization() {
  const params = {
    projectName: 'claude-zen-mvc-app',
    basePath: '/tmp/claude-zen-mvc-app',
    swarmConfig: {
      topology: 'hierarchical' as const,
      maxAgents: 8,
    },
    agentTypes: ['architect', 'researcher', 'coder', 'analyst', 'tester'],
    fileStructure: {
      '/tmp/claude-zen-mvc-app/src/models': null,
      '/tmp/claude-zen-mvc-app/src/views': null,
      '/tmp/claude-zen-mvc-app/src/controllers': null,
      '/tmp/claude-zen-mvc-app/src/utils': null,
      '/tmp/claude-zen-mvc-app/tests/unit': null,
      '/tmp/claude-zen-mvc-app/tests/integration': null,
      '/tmp/claude-zen-mvc-app/docs/api': null,
    },
    packageJson: {
      description: 'MVC application with claude-zen batch optimization',
      scripts: {
        build: 'tsc',
        dev: 'ts-node src/index.ts',
        test: 'jest',
        'test:watch': 'jest --watch',
        lint: 'eslint src',
        'start:prod': 'node dist/index.js',
      },
      dependencies: {
        express: '^4.18.0',
        typescript: '^5.0.0',
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/express': '^4.17.0',
        jest: '^29.0.0',
        eslint: '^8.0.0',
        'ts-node': '^10.0.0',
      },
    },
  };

  const result = await projectInitBatchTool.handler(params);
  if (result.success) {
    const response = result.content[0].text;
    // Extract metrics from response
    const speedMatch = response.match(/(\d+\.?\d*)x speed improvement/);
    const tokenMatch = response.match(/(\d+\.?\d*)% token reduction/);

    if (speedMatch) {
      result.performance.speedImprovement = Number.parseFloat(speedMatch[1]);
    }
    if (tokenMatch) {
      result.performance.tokenReduction = Number.parseFloat(tokenMatch[1]);
    }
  }

  return result;
}

/**
 * Main example runner
 * Runs all examples to demonstrate claude-zen capabilities
 */
export async function runClaudeZenExamples() {
  try {
    await exampleBasicClaudeZenPattern();
    await exampleProjectInitialization();
  } catch (error) {
    console.error('❌ Example execution failed:', error);
    throw error;
  }
}

// Export for use in other modules
export const ClaudeZenExamples = {
  exampleBasicClaudeZenPattern,
  exampleProjectInitialization,
  runClaudeZenExamples,
};

// Allow running directly with node
if (import.meta.url === `file://${process.argv[1]}`) {
  runClaudeZenExamples().catch(console.error);
}
