name: DAA WASM Integration CI/CD

on:
  push:
    branches: [main, ruv-swarm-v1.05-daa]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.75.0
      with:
        targets: wasm32-unknown-unknown
        components: rustfmt, clippy
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: npm/package-lock.json
    
    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Install wasm-opt
      run: |
        npm install -g wasm-opt
    
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build WASM DAA module
      run: |
        cd ruv-swarm
        ./build-wasm-optimized.sh
    
    - name: Run Rust tests
      run: |
        cd ruv-swarm
        cargo test --all-features
    
    - name: Install npm dependencies
      run: |
        cd ruv-swarm/npm
        npm ci
    
    - name: Run comprehensive tests
      run: |
        cd ruv-swarm/npm
        npm run test:comprehensive
    
    - name: Generate coverage report
      run: |
        cd ruv-swarm/npm
        npm run test:coverage:full
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./ruv-swarm/npm/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    - name: Run performance benchmarks
      run: |
        cd ruv-swarm/npm
        npm run test:performance
    
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          ruv-swarm/npm/test-reports/
          ruv-swarm/npm/coverage/
    
    - name: Check WASM size
      run: |
        ls -lh ruv-swarm/crates/ruv-swarm-wasm/pkg/*.wasm
        size=$(stat -c%s ruv-swarm/crates/ruv-swarm-wasm/pkg/ruv_swarm_wasm_bg.wasm)
        if [ $size -gt 200000 ]; then
          echo "WARNING: WASM size exceeds 200KB target"
        fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Build WASM module
      run: |
        cd ruv-swarm
        ./build-wasm-optimized.sh
    
    - name: Publish to npm
      run: |
        cd ruv-swarm/npm
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}