[package]
name = "code-mesh-cli"
version = "0.1.0"
authors = ["claude-code-zen Team"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Command-line interface for the Code-Mesh distributed swarm intelligence system"
homepage = "https://github.com/ruvnet/code-mesh"
repository = "https://github.com/ruvnet/code-mesh"
documentation = "https://docs.rs/code-mesh-cli"
readme = "README.md"
keywords = ["cli", "swarm", "distributed", "neural", "performance"]
categories = ["command-line-utilities", "development-tools", "concurrency"]

[[bin]]
name = "code-mesh"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
code-mesh-core = { version = "0.1.0", path = "../code-mesh-core" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5.0"
which = "6.0"

# CLI specific
clap = { version = "4.5", features = ["derive", "cargo"] }
indicatif = "0.17"
console = "0.15"
dialoguer = "0.11"

# Terminal UI
ratatui = "0.26"
crossterm = "0.27"
tui-textarea = "0.5"
syntect = "5.2"

# HTTP server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Utils
open = "5.1"
colored = "2.1"
chrono = { version = "0.4", features = ["serde"] }
atty = "0.2"
terminal_size = "0.3"
base64 = "0.22"
sha2 = "0.10"
rand = "0.8"
url = "2.5"
reqwest = { version = "0.12", features = ["json"] }

[dev-dependencies]
tempfile = "3.8"
assert_cmd = "2.0"
predicates = "3.0"
proptest = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }
mockall = "0.12"
assert_fs = "1.1"
insta = "1.34"
rstest = "0.18"