# Markdown Linting Configuration for Document-Driven Development
# Ensures consistent formatting and quality across all document types

# Line length - allow longer lines for tables and technical content
line-length:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

# Heading styles
heading-style:
  style: "atx"

# Unordered list style
unordered-list-style:
  style: "dash"

# Ordered list style  
ordered-list-style:
  style: "ordered"

# Allow duplicate headings in different sections
no-duplicate-heading:
  siblings_only: true

# Allow inline HTML for templates and formatting
no-inline-html: false

# Allow bare URLs in reference sections
no-bare-urls: false

# Custom rules for document templates
rules:
  # Require proper document headers
  MD041: false  # Allow documents without level 1 headings at start
  
  # Allow template placeholders like [Date], [Name]
  MD034: false  # Bare URL used - needed for template placeholders
  
  # Allow trailing punctuation in headers for template formatting
  MD026: false
  
  # Allow emphasis used instead of header
  MD036: false
  
  # Allow multiple blank lines for template structure
  MD012: false
  
  # Allow dollar signs in code blocks for examples
  MD014: false

# Document type specific configurations
overrides:
  - files: ["**/templates/*.md"]
    rules:
      # Templates can have placeholder syntax
      MD034: false  # Bare URL used
      MD040: false  # Fenced code blocks should have a language specified
      MD046: false  # Code block style
  
  - files: ["**/01-vision/*.md"]
    rules:
      # Vision docs tend to be longer
      MD013:
        line_length: 150
  
  - files: ["**/02-adrs/*.md"] 
    rules:
      # ADRs have specific format requirements
      MD025: false  # Multiple top level headings
      
  - files: ["**/03-prds/*.md"]
    rules:
      # PRDs can be very long with many sections
      MD013:
        line_length: 150
      MD012: false  # Multiple consecutive blank lines
      
  - files: ["**/06-tasks/*.md", "**/07-specs/*.md"]
    rules:
      # Technical docs can have code blocks and longer lines
      MD013:
        line_length: 150
        code_blocks: false