[package]
name = "ruv-swarm-daa-wasm"
version = "1.0.4"
edition = "2021"

[lib]
name = "ruv_swarm_daa_wasm"
crate-type = ["cdylib"]
path = "src-wasm/lib.rs"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console_error_panic_hook = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
