[package]
name = "ruv-swarm-daa-wasm"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"  # Optimize for size
lto = true       # Enable Link Time Optimization
codegen-units = 1
strip = true     # Strip symbols for smaller size

[features]
simd = ["wasm-bindgen/simd"]
default = ["console_error_panic_hook"]

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Window",
  "Document",
  "Performance",
  "PerformanceTiming",
]