---
name: "Claude Autonomous Agent v11"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        default: '147'

jobs:
  claude-solver:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
      metadata: read
      statuses: write
      checks: write
      id-token: write

    steps:
      - name: Debug Event
        run: |
          echo "🚀 CLAUDE AUTONOMOUS AGENT v11 ACTIVATED"
          echo "Event: ${{ github.event_name }}"
          echo "Issue: ${{ github.event.inputs.issue_number }}"

      - name: Claude Code Agent
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            🚀 CLAUDE CODE CLI AGENT v11 - Autonomous Issue Resolution
            
            **Issue #${{ github.event.inputs.issue_number }}**
            
            ## Mission
            You are Claude Code CLI Agent - implement the requested functionality.
            
            For issue #147: Create a simple add function that takes two numbers and returns their sum.
            Include comprehensive tests for this function.
            
            Follow these steps:
            1. Create the add function in appropriate location
            2. Write tests for the function
            3. Ensure everything works
            4. Commit changes and create pull request
            
            Execute autonomously. Deliver working code.