---
name: "Claude Test Manual v8"

on:
  workflow_dispatch:

jobs:
  test-minimal:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Test Basic Setup
        run: |
          echo "🧪 Testing Claude Code Action with agent mode"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: Claude Code Action Minimal
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: "agent"  # ⚡ CRITICAL: Use agent mode for workflow_dispatch
          direct_prompt: "Hello Claude! Please just echo 'Claude Code Action is working!' and create a simple test file called test-success.txt with the content 'Workflow v8 successful!'."