name: Claude Code Official

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && (github.event.action == 'opened' || 
       (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'claude-code')))) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request')
    
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Specify Claude model
          # model: claude-3-5-sonnet-20241022
          # Optional: Custom system prompt
          # system-prompt: |
          #   You are a helpful coding assistant. Follow the project's CLAUDE.md file for guidelines.