---
name: "Claude Autonomous Agent v13"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        default: '147'

jobs:
  claude-solver:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Setup Autonomous Agent
        run: |
          echo "🚀 Claude Autonomous Agent v13 ACTIVATED"
          echo "Processing Issue: ${{ github.event.inputs.issue_number }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: Claude Code Autonomous Agent
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: "agent"
          direct_prompt: |
            🚀 CLAUDE CODE CLI AGENT v13 - Autonomous Issue Resolution
            
            **Processing Issue #${{ github.event.inputs.issue_number }}**
            
            ## Mission
            You are an autonomous development agent. For issue #147, implement a simple add function.
            
            ## Task Details
            1. Create a function that adds two numbers
            2. Write comprehensive tests for the function
            3. Place in appropriate location in the claude-zen project structure
            4. Ensure code follows project conventions
            5. Create meaningful commit and pull request
            
            ## Project Context
            This is claude-zen - an AI development coordination system.
            Follow the existing patterns and structure.
            
            Execute autonomously. Deliver working, tested code.