---
name: "Claude Test Minimal v7"

on:
  workflow_dispatch:

jobs:
  test-minimal:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write  # ⚡ CRITICAL: Required for Claude Code Action OIDC

    steps:
      - name: Test Basic Setup
        run: |
          echo "🧪 Testing minimal Claude Code Action setup with id-token permission"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: Claude Code Action Minimal
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: "Hello Claude! Please just echo 'Claude Code Action is working!' and create a simple test file called test-success.txt with the content 'Workflow v7 successful!'."