name: Copilot Continue Pinger

on:
  schedule:
    - cron: "*/21 * * * *" # Every 10 minutes
  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request number to ping"
        required: false
        default: "51"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Comment "@copilot continue now" on PR #51
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number((context.payload && context.payload.inputs && context.payload.inputs.pr) || 51)

            // Ensure PR exists and is open; otherwise skip
            try {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              })
              if (pr.state !== 'open') {
                core.info(`PR #${prNumber} is ${pr.state}; skipping.`)
                return
              }
            } catch (e) {
              core.warning(`PR #${prNumber} not found: ${e.message}`)
              return
            }

            const body = '@copilot continue the task'
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body,
            })
            core.info(`Commented on PR #${prNumber}: ${body}`)
