name: Issue Access Control
# Security validation for issue access and permissions

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  check-issue-access:
    runs-on: ubuntu-latest
    if: github.event.issue.user.login != 'mikkihugo'
    
    steps:
      - name: Close unauthorized issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Close the issue immediately
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed',
              labels: ['unauthorized', 'auto-closed']
            });
            
            // Add explanatory comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🔒 **Access Restricted**
              
              This repository is configured for **restricted access**.
              
              **Issue automatically closed because:**
              - Only authorized users can create issues
              - User: @${context.payload.issue.user.login} is not authorized
              - Repository owner: @mikkihugo
              
              **📋 Repository Policy:**
              - Issues can only be created by repository owner
              - All authorized issues are automatically processed by Claude Code AI
              - Full automation: Issue → AI Analysis → PR → Auto-merge to main
              
              **🤖 For authorized users:**
              - Create any issue and Claude Code handles everything automatically
              - Zero manual intervention required
              - 3-5 minute resolution time
              
              If you believe this is an error, please contact the repository owner.
              
              🤖 **Auto-closed by Issue Access Control**`
            });
            
            console.log(\`Closed unauthorized issue #\${context.issue.number} from user: \${context.payload.issue.user.login}\`);