name: Test Automation Debug

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'claude-code')
    
    steps:
      - name: Test step
        run: |
          echo "🧪 Test automation triggered!"
          echo "Issue: #${{ github.event.issue.number }}"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Author: ${{ github.event.issue.user.login }}"
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"